spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/employee_overtime
spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=8081


